# Generated by Django 4.2 on 2024-07-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
    ]
