# Generated by Django 4.2 on 2024-07-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userinfos_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quantity_visits',
            field=models.IntegerField(default=0),
        ),
    ]
