# Generated by Django 4.2 on 2024-07-06 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_quantity_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=40),
        ),
    ]
