# Generated by Django 4.2 on 2024-07-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=600)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=40)),
                ('profile_photo', models.ImageField(default='', upload_to='')),
                ('description', models.CharField(default='', max_length=600)),
                ('creator_profile', models.BooleanField(default=False)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('private_account', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=600)),
                ('commented_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instamain.comment')),
                ('profile_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instamain.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instamain.user'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(default='', max_length=600)),
                ('profile_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instamain.profile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instamain.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instamain.profile'),
        ),
    ]
