# Generated by Django 4.2 on 2024-07-06 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('instamain', '0002_user_infos_profile_private_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_infos',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='profile_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='user_infos',
        ),
    ]
