# Generated by Django 4.2 on 2024-07-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instamain', '0003_remove_user_infos_user_alter_comment_profile_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
