# Generated by Django 4.2 on 2024-07-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instamain', '0004_post_comments_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='None', max_length=600),
        ),
    ]
