# Generated by Django 4.2 on 2024-07-19 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_friendship'),
        ('instamain', '0005_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(default='', upload_to='medias/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='profiles.profile'),
        ),
        migrations.CreateModel(
            name='ListLikesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instamain.post')),
                ('profile_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
